[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "arts"
version = "2024.2.13.2"
description = "对 Python 开发中常用功能的封装"
dependencies = ["openai>=1.2.4", "numpy", "pymysql", "aiomysql", "pyppeteer", "tornado"]

readme = "README.md"
authors = [{name = "江南雨上", email = "lcctoor@outlook.com"}]

[project.urls]
HomePage = "https://github.com/lcctoor/arts/tree/main/arts"