[tool.poetry]
name = "deciphon-snap"
version = "0.9.0"
description = "Reader for Deciphon snap files."
authors = ["Danilo Horta <horta@ebi.ac.uk>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "deciphon_snap" }]

[tool.poetry.dependencies]
fsspec = { version = ">=2024.2.0" }
python = "^3.9"
h3result = ">=0.3.1"
hmmer-tables = "^0"
tabulate = "^0"
fasta-reader = "^3.0.2"
deciphon-intervals = "^0.1.0"
prettytable = "^3.9.0"
pydantic = "^2.6.1"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
