[project]
name = "p5two"
version = "0.0.2"
description = "Automatically launch p5js sketches written in python"
readme = "README.md"
requires-python = ">=3.8"
keywords = ["p5js", "generative art", "creative coding"]
dependencies = [
    "pywebview",
    "transcrypt",
    "websockets",
    "watchdog"
]

[project.urls]
Homepage = "https://github.com/lorenzoferrone/p52"

[tool.setuptools.package-data]
"p52.static" = ["index.html"]