[project]
name = "brickschema-rdflib-sqlalchemy"
version = "0.6.0a1"
description = "rdflib extension adding SQLAlchemy as an AbstractSQLStore back-end store"
dependencies = [
    "SQLAlchemy>=2.0",
    "alembic>=0.8.8",
    "rdflib>=6, <8",
    "six>=1.10.0",
    "flake8>=5.0.4",
    "tox>=4.12.1",
    "setuptools>=69.0.3",
    "pytest>=8.0.0",
]
readme = "README.md"
requires-python = ">= 3.8"
license = { text = "BSD" }

#[project.scripts]
#hello = "rdflib-sqlalchemy:hello"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/rdflib_sqlalchemy"]
