[tool.poetry]
name = "wordfinderrz"
version = "0.1.18"
description = ""
authors = ["Sam <sbrobson@crimson.ua.edu>"]

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.scripts]
wordfinderrz = "wordfinderrz.gui:main"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.ruff]
preview = true

[tool.ruff.lint]
select = ["I", "B", "N", "A"]


[tool.mypy]
strict = true
python_version = "3.12"
