[package]
name = "chik-wallet"
version = "0.5.0"
edition = "2021"
license = "Apache-2.0"
description = "Chik primitives needed for building wallets."
authors = ["Brandon Haggstrom <b.haggstrom@chiknetwork.com>"]
homepage = "https://github.com/Chik-Network/chik_rs/chik-wallet/"
repository = "https://github.com/Chik-Network/chik_rs/chik-wallet/"

[dependencies]
klvmr = "0.4.0"
sha2 = "0.10.8"
num-bigint = "0.4.3"
hex-literal = "0.4.1"
klvm-utils = { version = "0.4.0", path = "../klvm-utils" }
klvm-traits = { version = "0.3.3", path = "../klvm-traits", features = ["chik-bls"] }
chik-bls = { version = "0.4.0", path = "../chik-bls" }
chik-protocol = { version = "0.5.0", path = "../chik-protocol" }
arbitrary = "1.3.0"

[dev-dependencies]
hex = "0.4.3"

[lib]
crate-type = ["rlib"]
