[tool.poetry]
name = "dimwit"
version = "0.2.0"
description = "A package containing various functions and classes for fetching, transforming, and visualising data for personal metrics."
authors = ["Daniel Soutar <danielsoutar144@gmail.com>"]
readme = "README.md"
repository = "https://github.com/danielsoutar/dimwit"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.1.4"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
