[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dbrequest"
version = "0.1.1"
authors = [
    { name="korandr", email="korandrmail@ya.ru" },
]
description = "Abstraction from DBMS, queries without explicit use of SQL, and convenient work with high-level object-containers."
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Topic :: Database",
    "Topic :: Documentation"
]

[project.urls]
Github = "https://github.com/korandr/dbrequest"
Documentation = "https://icy-cymbal-88c.notion.site/dbrequest-cde47cf005ad45c9a81d02c009ba9966?pvs=4"

