[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "smart_energy.data_vald3nir"
version = "1.0.0"
authors = [
  { name="Valdenir Severino", email="vald3nir@gmail.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

#[tool.hatch.build.targets.wheel]
#packages = ["src/smart_energy_data_vald3nir"]

[project.urls]
Homepage = "https://github.com/vald3nir/Smart-Energy-Data"
Issues = "https://github.com/vald3nir/Smart-Energy-Data/issues"

[pypi]
username = "__token__"
password = "pypi-AgEIcHlwaS5vcmcCJDBjYmU4OGNjLWU0NmItNDJmNC1iYjc2LWQzMWMyOTc2ZDhkMwACKlszLCJiMWQ0NTViMy0xYjI5LTRhYjQtOGNlZi0wN2QxMTY1YmEzZjEiXQAABiBYoQ0zY_W_zJe2wrMeWbhjhK5WLNaveQQDpqKSscy9ig"
