[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "miumapp"
version = "1.0.4"
description = "一个使用 Python + HTML + CSS + JavaScript 开发桌面应用的框架"
dependencies = ["arts>=2024.2.13", "pyppeteer"]
keywords = ["electron", "flutter", "uniapp", "pyqt", "miumapp"]

readme = "README.md"
authors = [{name = "江南雨上", email = "lcctoor@outlook.com"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: Apache Software License"]

[project.urls]
HomePage = "https://github.com/lcctoor/arts/tree/main/arts/miumapp"