[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "removeoverlap"
version = "0.0.15"
authors = [
  { name="Assem Hebik", email="assimhabe@gmail.com" },
]
description = "Decompose intersecting hyperrectangles"
readme = "README.MD"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/assimhabeek/remove-overlap"
Issues = "https://github.com/assimhabeek/remove-overlap/issues"


[tool.hatch.build.targets.wheel]
packages = ["src/removeoverlap"]