[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tm_parser"
version = "0.9.0"
dependencies = [
	"click~=8.1",
	"pyyaml~=6.0",
	"more_itertools",
	"pymupdf",
	"toml~=0.10",
	"python_dotenv",
	]
	

requires-python = ">3.9"
authors = [
	{name = "Michael Perkins", email="perkinsms@gmail.com"},
	]
maintainers = [
	{name = "Michael Perkins", email="perkinsms@gmail.com"},
	]

description = "Parse Troopmaster export files into TOML, YAML, or JSON"
license = {text = "MIT License"}

classifiers = [
	"Development Status :: 4 - Beta",
	"License :: OSI Approved :: MIT License",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3.9",
	"Programming Language :: Python :: 3.10",
	"Programming Language :: Python :: 3.11",
	]


[project.urls]
Repository = "https://gitlab.com/perkinsms/tm_parser"

[project.scripts]
tmparse = "tm_parser:__main__.main"



