[package]
name = "klvm-traits"
version = "0.3.3"
edition = "2021"
license = "Apache-2.0"
description = "Traits for encoding and decoding KLVM objects."
authors = ["Brandon Haggstrom <b.haggstrom@chiknetwork.com>"]
homepage = "https://github.com/Chik-Network/chik_rs/klvm-traits/"
repository = "https://github.com/Chik-Network/chik_rs/klvm-traits/"

[package.metadata.docs.rs]
features = ["derive", "chik-bls"]

[features]
derive = ["dep:klvm-derive"]
chik-bls = ["dep:chik-bls"]
py-bindings = ["dep:pyo3"]

[dependencies]
pyo3 = { version = ">=0.19.0", optional = true }
klvm-derive = { version = "0.2.14", path = "../klvm-derive", optional = true }
chik-bls = { version = "0.4.0", path = "../chik-bls", optional = true }
num-bigint = "0.4.3"
thiserror = "1.0.44"

[dev-dependencies]
hex = "0.4.3"
hex-literal = "0.4.1"
