[project]
name = "XspecT"
version = "0.1.2"
description = "Tool to monitor and characterize pathogens using Bloom filters."
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE"}
requires-python = ">=3.10"
dependencies = [
    "Flask",
        "Flask-WTF",
        "WTForms",
        "Werkzeug",
        "biopython",
        "bitarray",
        "mmh3",
        "numpy",
        "pandas",
        "requests",
        "scikit-learn",
        "Psutil",
        "Matplotlib",
        "Pympler",
        "H5py",
        "Bio",
        "wheel",
        "loguru",
        "Pympler",
        "click",
    ]
  classifiers = [
          "Intended Audience :: Developers",
          "Topic :: Scientific/Engineering :: Bio-Informatics",
          "License :: OSI Approved :: MIT License",
  ]

[project.urls]
Repository = "https://github.com/BIONF/XspecT2.git"

[project.scripts]
xspect = "xspect.main:cli"

[tool.setuptools.package-data]
"*" = ["*.html", "*.js", "*.png", "*.css"]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = [
  "src"
]

[project.optional-dependencies]
docs = ["sphinx", "furo", "myst-parser", "sphinx-copybutton", "sphinx-autobuild"]
test = ["pytest", "pytest-cov"]
