[tool.poetry]
name = "ImgWebp"
version = "0.2.2"
description = ""
authors = ["yuanhang <295043131@qq.com>"]
readme = "README.md"
packages = [{include = "ImgWebp", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
wget = "^3.2"
cleo = "^2.1.0"
pyqt5 = "^5.15.10"


[tool.poetry.scripts]
imgc = "ImgWebp.console.application:main"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
priority = "default"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
