[tool.poetry]
name = "freddy_camera"
version = "0.2.0"
description = ""
authors = ["megahomyak <g.megahomyak@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
Pillow = "^10.0.0"
pyvirtualcam = {extras = ["numpy"], version = "0.9.1"}
sounddevice = "^0.4.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
